export const IS_MAINTENANCE: boolean = false;
export const PLAYERS_PER_GROUP: number = 100;
export const JWT_SECRET: string =
  "5d82a2a96345715f0aa25c65a2c7568fca2fa10cf14c78ee57769cf9053cb6952f9c4a31baf9463d9b3d280ca337c05b8b1b125aa5b06c0588a4856da07428b2";

export enum TournamentSignUpStatus {
  NotSigned = 0,
  Ok = 1,
  InvalidTournamentIdOrData = 2,
  RequirementsNotMet = 3,
  NotEnoughtForEntry = 4,
  NotOpenedForSignUp = 5,
  TournamentIsFull = 6,
  DatabaseError = 7,
}
export enum TournamentType {
  GenericTournament,
  PremiumTournament,
  PrivateTournament,
  TestingTournament,
}
export enum TournamentStatus {
  Unknown = -1,
  NotStarted,
  InvitationOpen,
  InvitationClose,
  Finished,
  Canceled,
  Running,
}
export enum TournamentPhaseType {
  Arena = 1,
  SingleEliminationBracket,
  RoundRobin,
  DoubleEliminationBracket,
  DynamicBrackets,
}
export enum TournamentUserStatus {
  Unkown = -1,
  Invited,
  Confirmed,
  Declined,
  PartyNotFull,
  ProcessingSignup,
  ProcessingSignupFail,
  ProcessingSignout,
  ProcessingSignoutFail,
  KickedOutByAdmin,
}
export enum TournamentHubMatchStatus {
  NotInitialized,
  ConnectingToGameServerNetwork,
  ConnectingToMatch,
  ConnectedWaitingForTeamatesToCheckIn,
  ConnectedWaitingForMatchToFill,
  ConnectedWaitingForStart,
  ConnectedStartingMatch,
  ConnectedMatchInProgress,
  ConnectedMatchFinished,
  PartyNotReadyInTime,
}

export enum TournamentMatchStatus {
  Unkown = -1,
  Created,
  WaitingForOpponent,
  GameReady,
  GameInProgress,
  GameFinished,
  MatchFinished,
  Closed = 8,
}

export enum TournamentCreatePartyCodeStatus {
  Unknown = -1,
  NotAttempted,
  Ok,
  InvalidTournamentId,
}
export enum TournamentAcceptPartyStatus {
  Unknown = -1,
  NotAttempted,
  Ok,
  InviteNotExits,
  InviteIsMalformed,
  PartyIsFull,
  PartyNoLongerExits,
  TournamentRegistrationClosed,
  UserIsNotSignedUp,
}

export enum TournamentMode {
  OneVsOne = 1,
  TwoVsTwo = 2,
  ThreeVsThree = 3,
  FourVsFour = 4,
}

export enum OverrideTournamentMode {
  None,
  Elimination,
}

export enum MapTypes {
  Elimination = "Elimination",
  Race = "Race",
  Team = "Team",
  Collect = "Collect",
  Driving = "Driving",
  Shooter = "Shooter",
  Race_Survive = "Race_Survive",
}

export enum SceneTypes {
  "L_037_UFO2" = "Race",
  "level28_ufo" = "Race",
  "L_049_AcidPool" = "Elimination",
  "IPL_031_Plastic" = "Elimination",
  "level27_orange" = "Shooter",
  "IPL_034_OrangeGravity" = "Shooter",
  "level19_block" = "Elimination",
  "eventlevel8_block_endless" = "Elimination",
  "eventlevel13_block_legendary" = "Elimination",
  "level12_bomb" = "Elimination",
  "level22_bot" = "Elimination",
  "IPL_041_Cheese3" = "Elimination",
  "level29_rollingtowers" = "Race",
  "level6_hill" = "Race",
  "eventlevel9_cannonchaos" = "Race",
  "L_035_beachCarnival" = "Race",
  "IPL_039_Cheese1" = "Race",
  "IPL_033_OrangeDM" = "Shooter",
  "level9_seesaw" = "Race",
  "level8_honey" = "Elimination",
  "level23_wheels" = "Driving",
  "IPL_047_Flame" = "Driving",
  "level4_pushy" = "Race",
  "SSL_016_IceSki" = "Race",
  "level3_ice" = "Race",
  "level18_jungle" = "Race",
  "eventlevel1_dash" = "Elimination",
  "level15_laser" = "Elimination",
  "level21_pillar" = "Elimination",
  "level11_lava" = "Race",
  "level16_temple" = "Race",
  "IPL_038_Capital" = "Race",
  "IPL_044_Coconut" = "Race",
  "level32_mall" = "Race",
  "level6_hill_nfl" = "Race",
  "level7_moving" = "Race",
  "IPL_050_Pizza" = "Collect",
  "level20_paint" = "Race",
  "level5_pivot" = "Race",
  "StumblePrivDash" = "Race",
  "StumblePrivHour" = "Race",
  "StumblePrivLegendaryDash" = "Race",
  "StumblePrivTracer" = "Race",
  "level24_streamtiles" = "Elimination",
  "L_036_purple" = "Shooter",
  "SSL_011_SharkPirate" = "Elimination",
  "SSL_014_Sharktanic" = "Elimination",
  "eventlevel12_collectionRocket" = "Collect",
  "eventlevel4_honeylg_hard" = "Elimination",
  "eventlevel3_honeylg_medium" = "Elimination",
  "eventlevel2_honeylg_easy" = "Elimination",
  "level13_gravity" = "Race",
  "level1_whirly" = "Race",
  "level30_Jumping" = "Race",
  "eventlevel10_terrortumble" = "Race",
  "SSL_017_Vertigo" = "Race_Survive",
  "SSL_017_Vertigo_Easy" = "Race_Survive",
  "eventlevel6_lavasl" = "Race",
  "eventlevel5_paintsl" = "Race",
  "eventlevel7_pivotsl" = "Race",
  "level14_slide" = "Race",
  "SSL_015_slides" = "Race",
  "IPL_048_Protractor" = "Elimination",
  "L_042_Chicken" = "Elimination",
  "level2_tile" = "Race",
  "level25_collectcarrots" = "Collect",
  "level26_JungleTemple" = "Driving",
  "L_43_UFO3" = "Elimination",
}

export enum Scenes {
  "Abducted Avenue" = "L_037_UFO2",
  "Abduction Avenue" = "level28_ufo",
  "Acid Pool" = "L_049_AcidPool",
  "Barbie Dream Dash" = "IPL_031_Plastic",
  "Blaster Base" = "level27_orange",
  "Blaster Base Zero" = "IPL_034_OrangeGravity",
  "Block Dash" = "level19_block",
  "Block Dash Endless" = "eventlevel8_block_endless",
  "Block Dash Legendary" = "eventlevel13_block_legendary",
  "Bombardment" = "level12_bomb",
  "Bot Bash" = "level22_bot",
  "Bucket Mayhem" = "IPL_041_Cheese3",
  "Burrito Bonanza" = "level29_rollingtowers",
  "Cannon Climb" = "level6_hill",
  "Cannonball Chaos" = "eventlevel9_cannonchaos",
  "Crab's Landing" = "L_035_beachCarnival",
  "Don't Be Jelly!" = "IPL_039_Cheese1",
  "Elimination Base" = "IPL_033_OrangeDM",
  "Floor Flip" = "level9_seesaw",
  "Honey Drop" = "level8_honey",
  "Hot Wheels Hustle" = "level23_wheels",
  "Hot Wheels Yeti Run" = "IPL_047_Flame",
  "Humble Stumble" = "level4_pushy",
  "Ice Caramba" = "SSL_016_IceSki",
  "Icy Heights" = "level3_ice",
  "Jungle Roll" = "level18_jungle",
  "Laser Dash" = "eventlevel1_dash",
  "Laser Tracer" = "level15_laser",
  "Lava Land" = "level21_pillar",
  "Lava Rush" = "level11_lava",
  "Lost Temple" = "level16_temple",
  "Monopoly Rush" = "IPL_038_Capital",
  "MrBeast's Dangerous Traps" = "IPL_044_Coconut",
  "MrBeast's Warehouse" = "level32_mall",
  "NFL Scramble" = "level6_hill_nfl",
  "Over & Under" = "level7_moving",
  "Pac-Man Power" = "IPL_050_Pizza",
  "Paint Splash" = "level20_paint",
  "Pivot Push" = "level5_pivot",
  "Priv Dash" = "StumblePrivDash",
  "Priv Hour" = "StumblePrivHour",
  "Priv Legendary Dash" = "StumblePrivLegendaryDash",
  "Priv Tracer" = "StumblePrivTracer",
  "Rush Hour" = "level24_streamtiles",
  "Scaffold Stumble" = "L_036_purple",
  "sh-ARRRRGH-ks!" = "SSL_011_SharkPirate",
  "Sharkmuda Triangle" = "SSL_014_Sharktanic",
  "SkyRocket Royale" = "eventlevel12_collectionRocket",
  "Space Droooooop" = "eventlevel4_honeylg_hard",
  "Space Drooop" = "eventlevel3_honeylg_medium",
  "Space Drop" = "eventlevel2_honeylg_easy",
  "Space Race" = "level13_gravity",
  "Spin Go Round" = "level1_whirly",
  "Stumble Cove" = "level30_Jumping",
  "Stumble Trouble" = "eventlevel10_terrortumble",
  "Stumble Up" = "SSL_017_Vertigo",
  "Stumble Up EZ" = "SSL_017_Vertigo_Easy",
  "Super Lava Slide" = "eventlevel6_lavasl",
  "Super Paint Slide" = "eventlevel5_paintsl",
  "Super Pivot Slide" = "eventlevel7_pivotsl",
  "Super Slide" = "level14_slide",
  "Super Waterpark" = "SSL_015_slides",
  "Tetris Tumble" = "IPL_048_Protractor",
  "The Other Side" = "L_042_Chicken",
  "Tile Fall" = "level2_tile",
  "Treasure Island" = "level25_collectcarrots",
  "Turbo Temple" = "level26_JungleTemple",
  "UFOMG!" = "L_43_UFO3",
}

export enum Emotes {
  "Only Punch & Kick" = -3,
  "Hug Only" = -5,
  "Banana Only" = -4,
  "Punch Only" = -2,
  "Special Emotes" = -1,
  "Happy" = 1,
  "Cry" = 2,
  "Angry" = 3,
  "Cool" = 4,
  "Thumbs Up" = 5,
  "Skull" = 6,
  "Crown" = 7,
  "Hug" = 8,
  "Punch" = 9,
  "Hi" = 10,
  "Ha Ha" = 11,
  "GG" = 12,
  "Kick" = 13,
  "Posing" = 14,
  "Backflip" = 15,
  "Sleeping" = 16,
  "Handstand" = 17,
  "Ripaska" = 18,
  "Spin" = 19,
  "Push Up" = 20,
  "Victory" = 21,
  "Thumbs Down" = 23,
  "Dab" = 24,
  "ROFL" = 25,
  "Let's Go" = 26,
  "RIP" = 28,
  "Boo" = 29,
  "Scared" = 31,
  "Red Card" = 32,
  "Foam Hand" = 33,
  "Happy Soccer Ball" = 34,
  "Sad Soccer Ball" = 35,
  "Too Cool" = 36,
  "Selfie" = 37,
  "Lay On Ground" = 38,
  "Laughing At You" = 39,
  "Shoulder Brush" = 41,
  "Butt Shake" = 42,
  "Plank" = 43,
  "<3" = 44,
  "Sit" = 45,
  "Let's Snow" = 46,
  "Merry Skull" = 47,
  "2023 Emote" = 48,
  "Santa Thumbs Up" = 49,
  "Cold" = 50,
  "Mad Cookie" = 51,
  "Present" = 52,
  "Poop" = 53,
  "LOL" = 54,
  "Banana" = 55,
  "Capybara" = 56,
  "Party Popper" = 57,
  "Year of the Rabbit" = 58,
  "Heart Eyes" = 59,
  "Holding Back" = 60,
  "Capybara Tie" = 61,
  "Oops!" = 62,
  "Zzzzzz" = 63,
  "Goal!" = 64,
  "Black Eye" = 65,
  "Football" = 66,
  "KO!" = 67,
  "Broken Heart" = 68,
  "OMG" = 69,
  "Red Packet" = 70,
  "Bow" = 72,
  "The Robot" = 73,
  "The Worm" = 74,
  "Big Chicken" = 75,
  "So Sad!" = 76,
  "Shadow Boxing" = 77,
  "Crane Kick" = 78,
  "Meditate" = 79,
  "My Crown!" = 80,
  "Guitar Solo!" = 81,
  "Champagne Shake" = 82,
  "Touchdown!" = 83,
  "Griddy Dance" = 84,
  "Fire Punch" = 85,
  "Angry Rabbid" = 86,
  "Gym Flex" = 87,
  "Samba Dance" = 88,
  "Happy Rabbid" = 89,
  "Sad Rabbid" = 90,
  "Hang Loose" = 91,
  "Happy Chibi" = 92,
  "Sad Chibi" = 93,
  "Mad Chibi" = 94,
  "DJ Moves" = 95,
  "Going Super" = 96,
  "Head Spin" = 97,
  "Surf Mime" = 98,
  "Bunny Hop" = 99,
  "The Macarena" = 100,
  "Neon Heart" = 101,
  "Neon Smiley Face" = 102,
  "Rainbow Wave" = 103,
  "PBJ Dance" = 104,
  "Get Sturdy Dance" = 105,
  "Good Luck" = 107,
  "Ninja Run" = 106,
  "April Fools" = 108,
  "Fool Guy Glasses" = 109,
  "Easter Egg" = 110,
  "Easter Bunny" = 111,
  "Angry Easter Bunny" = 112,
  "Storm Cloud" = 113,
  "Raspberries" = 114,
  "UWU" = 115,
  "RIP YOU" = 117,
  "Style Dance" = 118,
  "Fireworks Fire" = 119,
  "Tiny Bike" = 120,
  "You Like Me!" = 121,
  "Golden Banana" = 122,
  "Wet Kick" = 123,
  "Charged Hug" = 124,
  "Pizza" = 125,
  "Pirate" = 126,
  "Checkered Flag" = 127,
  "Good/Evil" = 128,
  "Flaming tire" = 129,
  "Bullseye" = 130,
  "bro........" = 131,
  "Burning Heart" = 132,
  "Twisted" = 133,
  "Rainbow" = 134,
  "3D Glasses" = 135,
  "No Cake 4U" = 136,
  "Make it Rain" = 137,
  "Side Wiggle" = 138,
  "Fireworks Show" = 139,
  "2B or Not 2B" = 140,
  "Exploding Money" = 141,
  "UFO Abduction" = 142,
  "MrBeast Case Legendary" = 143,
  "Stumble Praise" = 144,
  "Fire" = 145,
  "Devil" = 146,
  "Barf" = 147,
  "Unicorn Poop" = 148,
  "USA Shades" = 149,
  "Barbie Smile" = 150,
  "Girl Power" = 151,
  "The Beast" = 152,
  "Cash Money" = 153,
  "MrBeast" = 154,
  "MrBeast Case" = 155,
  "Ball" = 156,
  "Hamburger" = 157,
  "Ban Hammer" = 158,
  "EZ" = 160,
  "Money Case" = 161,
  "Seein' Stars" = 162,
  "Sad Ice Cream" = 163,
  "Money Gun" = 164,
  "Descending" = 165,
  "Super Thief" = 166,
  "Money Pallet" = 167,
  "Loser" = 168,
  "Share the Wealth" = 169,
  "Playing Monopoly" = 170,
  "I'm the boss" = 171,
  "Go To Jail" = 172,
  "Flip the Table" = 173,
  "Invisibility" = 174,
  "Strength of Atlas" = 175,
  "Zeus' Lightning" = 176,
  "Jokey's Smurfirrific Present" = 185,
  "Smurfette" = 186,
  "Kiai" = 187,
  "Smurferous Pow" = 188,
  "Go Blue" = 189,
  "Blah Bah Blah Bah Blah" = 190,
  "Stake through the Heart" = 191,
  "Ghost" = 192,
  "Bats And Moon" = 194,
  "Zombie Pop" = 195,
  "Witch's Brew" = 196,
  "Maniac killer" = 197,
  "Possessed" = 198,
  "Beast Lightning" = 217,
  "Beast Cracker" = 180,
  "Fire Cracker" = 177,
  "Mr Beast" = 178,
  "Feastibles" = 179,
  "Floor is Lava" = 181,
  "Spike Walls" = 182,
  "Big Red button" = 184,
  "Money Jump" = 183,
  "SpongeBob Waterworks" = 199,
  "Imagination" = 200,
  "Carving the Turkey" = 201,
  "Mariachi Dance of the Dead" = 202,
  "Catrin Dance of the Dead" = 203,
  "Diwali Dance" = 204,
  "Ripping a Fart" = 205,
  "Shocker" = 206,
  "Skateboard Kickflip" = 207,
  "Nunchucks" = 208,
  "Cheerleader" = 209,
  "Happy Diwali" = 211,
  "Happy Thanksgiving" = 212,
  "Turkey" = 213,
  "Spatula Slap" = 239,
  "Karate Chop" = 240,
  "Cactus Oooochhh!" = 210,
  "Blue Cat Mushroom Hat" = 246,
  "Sugar Skull" = 244,
  "Diwali Candle" = 242,
  "Clown" = 214,
  "Sweaty Grin" = 216,
  "Handsome Squidward" = 235,
  "Surprised Patrick" = 236,
  "Surprised Spongebob" = 237,
  "Gary" = 238,
  "Happy Dia De Los Muertos" = 243,
  "Snowball Throw" = 234,
  "Toss a Block" = 218,
  "Snake" = 250,
  "Moshpit" = 251,
  "RightLeftSlide" = 215,
  "GiddyUp" = 247,
  "The Sprinkler" = 249,
  "TheBow" = 248,
  "Cool... Cool... Cool..." = 252,
  "Mooooo!!!!" = 232,
  "Flying Snowball" = 233,
  "Here Comes Santa Claus" = 225,
  "Bacon!!!" = 228,
  "Candy Cane" = 224,
  "Happy Holidays" = 222,
  "Warm Fire" = 230,
  "Happy Ninja Day" = 227,
  "Hot Cocoa" = 229,
  "Honk Honk!!!" = 231,
  "Freezing" = 226,
  "2024 Emote" = 219,
  "Merry Christmas" = 220,
  "Happy Hanukkah" = 221,
  "Happy Kwanzaa" = 223,
  "PAC-MAN" = 253,
  "The End" = 241,
  "Corgi Floof" = 255,
  "Force Shield" = 254,
}

export enum Regions {
  "Europe" = "eu",
  "Middle East" = "tr",
  "North America" = "us",
  "Us West" = "usw",
  "Central America" = "ussc",
  "South America" = "sa",
  "Asia" = "asia",
  "India" = "in",
}
